# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

# rake figaro:heroku to push these to Heroku

development:
  TWITTER_KEY: op0vTryktD5ZwrNiUTJlMT2Gr
  TWITTER_SECRET: 9gIfBbjCoFIUaYSeEAFT7EYCFiBXi6gidQ9IUzJahOFthQDqwl
  FACEBOOK_KEY: 825805507448180
  FACEBOOK_SECRET: 2eb5911ed3c4bc51e120a064caef8592

test:
  TWITTER_KEY: op0vTryktD5ZwrNiUTJlMT2Gr
  TWITTER_SECRET: 9gIfBbjCoFIUaYSeEAFT7EYCFiBXi6gidQ9IUzJahOFthQDqwl
  FACEBOOK_KEY: 825805507448180
  FACEBOOK_SECRET: 2eb5911ed3c4bc51e120a064caef8592

production:
  TWITTER_KEY: op0vTryktD5ZwrNiUTJlMT2Gr
  TWITTER_SECRET: 9gIfBbjCoFIUaYSeEAFT7EYCFiBXi6gidQ9IUzJahOFthQDqwl
  FACEBOOK_KEY: 825805507448180
  FACEBOOK_SECRET: 2eb5911ed3c4bc51e120a064caef8592